### ISSUE TITLE
Could you provide the ROM contents, so that other could easily replicate the design?

### ISSUE THREAD

**Issue by marcin-chwedczuk** [TomNisbet/Simple8085#1]
In short I get 2 old 8085's ICs and I just want to verify that they work. Running old MS Basic can be an excellent way to do this. 

Looking at your project, I see that it's the simplest and yet fully functional 8085 based computer that I have ever seen. No part is redundant (OK we can get rid of RAM, but at the cost of Stack not working).

The only thing that is missing are ROMs that would allow someone to quickly replicate the design without spending hours looking for the original ROM and MS Basic. 

I am not sure if MS Basic is still copyright'able but if you cannot add them to the repo I understand that. In that case can you contact me at 0xmarcin at gmail.com please?

**Comment by TomNisbet** [comment]
I added an image of the current ROM in the hardware directory.  The ROM monitor is an extension of the original Explorer/85, with some new commands added.  Other commands that are not supported by this hardware, like single step, have been removed.  This is a bit of a work-in-progress.  The EEPROM burning code works, but it requires that a block of code if first copied out of the ROM so it can be executed from RAM.  This should be automatic, but if you just type GF800 after starting the monitor it will do the copy and then the EEPROM burn command should work.  ROM memory map is:

- 8000 - jump instruction to the monitor
- c000 - basic
- f000 - ROM monitor

**Comment by TomNisbet** [comment]
To test your 8085s, you may also want to take a look at the README where it describes the build process.  You can first wire your 8085 to free-run a NOP instruction and observe the address lines,  Then add the ROM and run some simple tests.  There are some examples in the asm85 repo.  Finally, you can build the complete Simple8085 and run it code.

**Comment by marcin-chwedczuk** [comment]
Thank you! I will check this out over the weekend :+1:
